dist: bionic
language: python

python:
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install --upgrade pip
  - pip install poetry>=1.0.0b1 # Using preview build to enable pypi api token usage
  - poetry install -v

script:
  - pytest --cov=fri -n 2

after_success:
  - coveralls

before_deploy:
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - portray as_html

deploy:
  - provider: script
    script: poetry publish
    skip_existing: true
    on:
      tags: true
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: site/
    github_token: $GH_TOKEN
    keep_history: true
    on:
      branch: master
