dist: bionic
language: python

python:
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install --upgrade pip
  - pip install poetry>=1.0.0b1 # Using preview build to enable pypi api token usage
  - poetry install -v

script:
  - pytest --cov=fri -n 2
  - travis-sphinx build -n --source=doc/source

after_success:
  - coveralls
  - travis-sphinx deploy

before_deploy:
  - poetry config pypi-token.pypi $PYPI_TOKEN

deploy:
  provider: script
  script: poetry publish
  skip_existing: true
  on:
    tags: true
    branch: master
